【目標作成機能】目標作成APIルートを作成
YoshijiFujiwara/himawari-project pull request #102
Opened 2020-06-15 12:52 UTC by shzawa

## :ticket: チケット
(trelloのチケットのリンクを貼りましょう)
https://trello.com/c/JfU0NLQs

## :memo: 概要
(やった内容を書こう！)
ログインしたユーザーのみができる目標作成機能

## :stuck_out_tongue: やってないこと
（この PR ではやってないことなどを明記しよう。相談の上、あえて他のPRで対応する予定のこととか）
目標作成以外の機能

## :heavy_check_mark: 動作確認
（実装した個々の機能の再現方法を明記し、開発者・レビュワー共に確認するのだ！）
- [ ] CIが通ること
- [ ] 動作確認
  - Swagger
    - [ ] 鍵マークを押してログイン時に取得できるTokenをsave
    - [ ] `Try it out`ボタンを押してexampleのまま(特に編集しなくてもOK)で`Execute`ボタンを押して201が返ってこればOK

2020-06-15 14:44 UTC, YoshijiFujiwara reviewed
動きOK
全体的にしっかり出来てます
goalRepositoryのあたりでちょっと修正するところがあるので、お願いします！

2020-06-15 14:44 UTC, YoshijiFujiwara commented on api/src/goals/goal.entity.ts
> +  @JoinColumn({ name: 'user_id' })
良さみ深子

2020-06-15 14:44 UTC, YoshijiFujiwara commented on api/src/goals/goal.repository.ts
> +    goal.userId = user.id;
ここ
```
goal.user = user
```
で書きたいお気持ちがありますね
 これでsave()すると、
goal.userに投稿者情報がいい感じに入りつつ、
user_idカラムにもユーザーIDが入るはずっす
そして、
```
goal.userId = user.id;
```
は不要になるっす

2020-06-15 14:44 UTC, YoshijiFujiwara commented on api/src/goals/goal.repository.ts
> +    try {
ああ、すいません
このあたりのtry catch、多分不要でした:sweat:

userRepositoryのcreateUserでtry catchしている理由は、err.codeを見て、メールアドレスの重複エラーとそれ以外の例外を区別したいからだったのですが、
今回の場合、とくにユニーク制約にかかる恐れがないので、try catchは不要ですね
もちろん、goal.save()がなんらかの形で失敗したら、500エラーの例外は発生するので、とくにtry catchで投げ直す必要がないということでした:bow:

上記のと合わせると、
```
goal.title = title;
goal.description = description;
goal.isPublic = isPublic;
goal.user = user;
await goal.save();

delete goal.user;
return goal;
```
ですみますね:+1:
`delete goal.user;`
に関しては、
目標の新規作成時に、フロントにユーザー情報も返したいケースは発生しなさそうなので、
repositoryの段階で消してます

もちろん、目標詳細情報を取得するときは（特に他人の）は、目標とその投稿者情報も欲しくなると思うので、
常に`delete goal.user`するというわけではないです

2020-06-15 14:44 UTC, YoshijiFujiwara commented on api/src/goals/goals.service.spec.ts.sub
> +import { UserEntity } from '../auth/user.entity';
一応、使わないファイルは消しておいてください！
あとで復活するときは、gitのログをみませう！

2020-06-15 14:56 UTC, YoshijiFujiwara commented
ちな動作はOKです

2020-06-15 15:04 UTC, shzawa commented on api/src/goals/goals.service.spec.ts.sub
> +import { UserEntity } from '../auth/user.entity';
了解です！

2020-06-15 15:07 UTC, shzawa commented on api/src/goals/goal.repository.ts
> +    goal.userId = user.id;
ですよね、最初そうしてたんですけど例のカラム名問題で原因分からなくなってたからとりあえず関係ありそうなやつ消してた名残で忘れてました、、

2020-06-15 15:08 UTC, YoshijiFujiwara commented on api/src/goals/goal.repository.ts
> +    goal.userId = user.id;
aruaru

2020-06-16 06:35 UTC, shzawa commented on api/src/goals/goal.repository.ts
> +    try {
修正しました❗

2020-06-16 06:36 UTC, YoshijiFujiwara commented
# [Codecov](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/102?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`develop@376ccb2`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/102/graphs/tree.svg?width=650&height=150&src=pr&token=ICPqkmgEhz)](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/102?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##             develop     #102   +/-   ##
==========================================
  Coverage           ?   50.11%           
==========================================
  Files              ?       36           
  Lines              ?      441           
  Branches           ?       30           
==========================================
  Hits               ?      221           
  Misses             ?      220           
  Partials           ?        0           
```

2020-06-16 11:34 UTC, YoshijiFujiwara requested changes
ファイナルオブラストコメントです
修正したあと、make codegenを忘れずにONSS:bow:

2020-06-16 11:34 UTC, YoshijiFujiwara commented on api/src/goals/goals.service.ts
> +    const goal = await this.goalRepository.createGoal(createGoalDto, user);
Serviceでは、GoalEntityを返しておいて、
Controllerで、Serializerに変更するって流れにしたいので、ここは
```
return await this.goalRepository.createGoal(createGoalDto, user);
```

として、controllerで返す時に、
```
const goalEntity = await this.goalsService.createGoal(createGoalDto, user);
return goalEntity.transformToSerializer();
```
でいいかなと思います

Service層で極力、Serializeとかフロントの用事を持ち込みたくなく、
その辺はControllerまでで解決するって方針です:+1:

2020-06-16 11:39 UTC, shzawa commented on api/src/goals/goals.service.ts
> +    const goal = await this.goalRepository.createGoal(createGoalDto, user);
getGoalの方でもそれやらかしてたんでpush次第修正します！あざす！

2020-06-16 11:40 UTC, YoshijiFujiwara commented on api/src/goals/goals.service.ts
> +    const goal = await this.goalRepository.createGoal(createGoalDto, user);
[memo]
まあ、controller側で、一行でかきたかったら、
```
return (
      await this.goalsService.createGoal(createGoalDto, user)
    ).transformToSerializer();
```
ともかけるけど、可読性下がってるので、上の
```
const goalEntity = await this.goalsService.createGoal(createGoalDto, user);
return goalEntity.transformToSerializer();
```
でよさそう

2020-06-16 11:44 UTC, shzawa commented on api/src/goals/goals.service.ts
> +    const goal = await this.goalRepository.createGoal(createGoalDto, user);
その書式よく適当に保存した際にフォーマットされて見る形だ…
ですねですね

2020-06-16 11:47 UTC, YoshijiFujiwara commented
こっちで
```
make codegen
```
すると差分が出るので、
確認ONSS

2020-06-16 12:33 UTC, YoshijiFujiwara approved these changes
LGTM
対応ありがとう！
[![LGTM](https://lgtm.in/p/QUDtHgZRp)](https://lgtm.in/i/QUDtHgZRp)

2020-06-16 12:38 UTC, merged

2020-06-16 12:38 UTC, shzawa commented
kusa