グループ作成のAPI
YoshijiFujiwara/himawari-project pull request #134
Opened 2020-06-22 04:00 UTC by YoshijiFujiwara

## :ticket: チケット
dummy: https://trello.com/c/Owg8nQo2
https://trello.com/c/oWmNYhQ6

## :memo: 概要
- グループ作成のAPIを追加
- グループ作成の、テストを追加
  - groups.controller.spec
  - groups.services.spec
  - group.repository.spec
  - group.entitty.spec

## :stuck_out_tongue: やってないこと
（この PR ではやってないことなどを明記しよう。相談の上、あえて他のPRで対応する予定のこととか）

## :heavy_check_mark: 動作確認
（実装した個々の機能の再現方法を明記し、開発者・レビュワー共に確認するのだ！）
- [ ] CIが通ること

- [x]  swaggerにて、以下の手順で動作確認を行う

`ログインしていないとき`
- [x] POST /api/goals  でリクエストすると、401エラーが返却されること

`ログインしているとき`
- [x] POST /api/goals  でリクエストすると、201ステータスで、新規登録したグループ情報が返却される
  - [x] 送信したグループ情報が、groupsテーブルに追加されていること
- [x] `name: ""`のように空文字をPOSTすると、バリデーションに引っかかること
- [x] nameが21文字以上でPOSTすると、バリデーションに引っかかること

2020-06-22 04:02 UTC, YoshijiFujiwara commented
# [Codecov](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/134?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`develop@dad93b7`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/134/graphs/tree.svg?width=650&height=150&src=pr&token=ICPqkmgEhz)](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/134?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##             develop     #134   +/-   ##
==========================================
  Coverage           ?   65.68%           
==========================================
  Files              ?       79           
  Lines              ?      819           
  Branches           ?       46           
==========================================
  Hits               ?      538           
  Misses             ?      281           
  Partials           ?        0           
```

2020-06-22 05:22 UTC, YoshijiFujiwara commented
@tk-ozawa 
more_more_testブランチから切っているので、
https://github.com/YoshijiFujiwara/himawari-project/pull/133
more_more_testブランチのマージしたあと（重要）
こちらのレビューをお願いします:bow:

- テストは流し見でおk
- それ以外のところはgoals.moduleなどと構成が同じなのでみやすいと思います

出ないと差分が大きくなります

2020-06-22 05:33 UTC, YoshijiFujiwara commented
pull origin develop
で差分を減らしました

2020-06-22 14:26 UTC, shzawa requested changes
コメント載せました。追加頼んます

2020-06-22 14:26 UTC, shzawa commented on api/src/groups/dto/create-group.dto.ts
> +  })
minLengthとmaxLengthのパラメータ付与お願いします！

2020-06-22 14:27 UTC, shzawa commented
動作確認:ok:

2020-06-22 15:07 UTC, YoshijiFujiwara commented on api/src/groups/dto/create-group.dto.ts
> +  })
わお！

2020-06-22 15:11 UTC, YoshijiFujiwara commented on api/src/groups/dto/create-group.dto.ts
> +  })
指摘ありがとう
追加しました！

2020-06-23 02:37 UTC, shzawa approved these changes
LGTM!

2020-06-23 02:40 UTC, YoshijiFujiwara commented
レビュー感謝

2020-06-23 02:40 UTC, merged