ユーザーをグループに招待する本物のAPI
YoshijiFujiwara/himawari-project pull request #147
Opened 2020-06-24 16:57 UTC by shzawa

## :ticket: チケット
(trelloのチケットのリンクを貼りましょう)
https://trello.com/c/fX5TQU1o
https://trello.com/c/VPC8E027

## :memo: 概要
(やった内容を書こう！)
- 招待先アカウントのメールアドレスをDB経由でのバリデーション(存在判定及び有効化判定)
- グループ招待(ユーザー追加)
- 招待通知メール送信

## :stuck_out_tongue: やってないこと
（この PR ではやってないことなどを明記しよう。相談の上、あえて他のPRで対応する予定のこととか）
- 通知メールの中におけるグループページへのリンク配置(グループのTOPページがまだなので)

## :heavy_check_mark: 動作確認
（実装した個々の機能の再現方法を明記し、開発者・レビュワー共に確認するのだ！）
- [ ] CIが通ること

### ログインしていない時

- [ ] POST `/api/groups/:id`で401エラー

### ログインしている時

1. ユーザーAを登録、有効化(メール認証パス)
1. ユーザーBを登録

上記の状態で、
- ユーザーAでログインし、POST `/api/groups`にてグループを作成。
- [ ] 作成したグループのIDから POST `/api/groups/:id`にてユーザーBのメールアドレスを指定し実行後、404エラー
- [ ] ユーザーBを有効後、ユーザーAでログインし、POST `/api/groups/:id`にてユーザーBのメールアドレスを指定し実行後、201が返ってくる
- [ ] DB上の`user_group`テーブルにて上記の内容が登録されているか
- [ ] mailTrapにて招待通知メールが届いているか

2020-06-24 16:59 UTC, YoshijiFujiwara commented
# [Codecov](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/147?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`develop@8cb36b6`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/147/graphs/tree.svg?width=650&height=150&src=pr&token=ICPqkmgEhz)](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/147?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##             develop     #147   +/-   ##
==========================================
  Coverage           ?   80.10%           
==========================================
  Files              ?       39           
  Lines              ?      593           
  Branches           ?       27           
==========================================
  Hits               ?      475           
  Misses             ?      118           
  Partials           ?        0           
```

2020-06-24 17:00 UTC, shzawa commented
また書いていただいてたspecファイルと喧嘩してるみたいなので確認お願いします〜〜〜〜🥺

2020-06-25 04:32 UTC, YoshijiFujiwara requested changes
何点かコメントしました
グループへの招待まわりでは、
- ログインユーザー自身がグループメンバーか
- 招待したいユーザーがまだ、未参加のユーザーであるか

などのチェックが必要なので、そのあたりの修正をお願いしまっす

2020-06-25 04:32 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +    if (user && !user.isEmailVerified) {
googleアカウントでログインしている場合、isEmailVerifyidカラムはfalseのままになっています
googleアカウントログインの場合は、`thirdPartyId`に値がはいっているので、そちらも考慮すると良さそうです
```
// メール認証が出来ていない && SNSアカウント連携ではないとき
if (!user || (!user.isEmailVerified && !user.thirdPartyId)) {
  throw new UnauthorizedException();
}
```
という感じかな

2020-06-25 04:32 UTC, YoshijiFujiwara commented on api/src/groups/groups.controller.ts
> +  @Post(':id/users')
RESTのURL設計に習うと、
POST /api/groups/:id/users が妥当かなと思います
:id のgroupになんのリソースを追加するのかが、 api/groups/:idだけだとわからないからです

たとえば、何かの投稿にコメントを追加するルートは、
POST /api/posts/:id/commits となると思います

この点は、テスト直すついでにこちらで修正しました

2020-06-25 04:32 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +      throw new UnauthorizedException('メール確認が出来ておりません');
`メール確認が出来ておりません`
の文言はなくても良さそうな気がしますね

他人のメール確認状況について、調べることができるとなんかいやなので
`throw new UnauthorizedException('');`
のようにぼかすと良さそうです

余談ですが、
`validatePassword`メソッドの方は、自分のパスワード確認なので、まあいいかと

2020-06-25 04:32 UTC, YoshijiFujiwara commented on api/src/groups/group.repository.ts
> +    group.users = [...group.users, user];
こういう書き方ができるようになってきましたか！
いいですね〜〜

2020-06-25 04:32 UTC, YoshijiFujiwara commented on api/src/groups/groups.service.ts
> +    user: UserEntity,
このログインuserが、該当のidのグループにすでに参加出来ている &&
招待するユーザーがまだそのグループに参加していない

場合のみ、招待できるようにする必要があると思うので、処理の追加お願いします！

2020-06-25 04:34 UTC, YoshijiFujiwara commented
テストは処理の修正ができてから、一気に直します

2020-06-25 06:06 UTC, shzawa commented on api/src/auth/user.repository.ts
> +    if (user && !user.isEmailVerified) {
あーその仕様頭から抜けてました、、、
帰宅次第修正します！あざす！

2020-06-25 06:07 UTC, shzawa commented on api/src/groups/groups.controller.ts
> +  @Post(':id/users')
groupコントローラのリソースパスの設定見てませんでした、、、了解です

2020-06-25 06:08 UTC, shzawa commented on api/src/auth/user.repository.ts
> +      throw new UnauthorizedException('メール確認が出来ておりません');
確かに他人のアカウントの状態知れるのはキモいっすね、了解っす

2020-06-25 06:08 UTC, shzawa commented on api/src/groups/groups.service.ts
> +    user: UserEntity,
それめっちゃ大事な仕様でした、、、
了解です実装します

2020-06-25 07:08 UTC, shzawa commented on api/src/groups/groups.controller.ts
> +  @Post(':id/users')
GroupsControllerってこれ@Controllerデコレータでリソース名指定してるんで、
Swagger見てもらったら確認できると思うんですけどしっかり`/api/groups/:id/users`ってなってますね

2020-06-25 07:08 UTC, shzawa commented on api/src/auth/user.repository.ts
> +      throw new UnauthorizedException('メール確認が出来ておりません');
:done:

2020-06-25 07:08 UTC, shzawa commented on api/src/auth/user.repository.ts
> +    if (user && !user.isEmailVerified) {
:done:

2020-06-25 07:09 UTC, shzawa commented on api/src/groups/group.repository.ts
> +    group.users = [...group.users, user];
褒められるのありがてえ〜〜〜〜〜〜

2020-06-25 08:43 UTC, shzawa commented on api/src/groups/groups.service.ts
> +    user: UserEntity,
なんかめっちゃ時間かかっちゃいました
:done:

2020-06-25 08:46 UTC, YoshijiFujiwara commented on api/src/groups/groups.controller.ts
> +  @Post(':id/users')
あ、これ
https://github.com/YoshijiFujiwara/himawari-project/pull/147/commits/ab312bb055dd378f86ff81bb7e957a4eefa64360
でワイが直しました

2020-06-25 08:51 UTC, shzawa commented on api/src/groups/groups.controller.ts
> +  @Post(':id/users')
aそうでしたかあざす！

2020-06-25 14:45 UTC, YoshijiFujiwara reviewed
テストの修正と同時に、一部変数名の修正をしました

2020-06-25 14:45 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +import { InviteGroupDto } from './dto/invite-group.dto';
気づくの遅れましたが、
inviteGroupではなく、inviteUser
のほうが命名としては良さそうです

Userを招待するためです

2020-06-25 14:48 UTC, YoshijiFujiwara approved these changes
動作確認できました！
対応乙
LGTM

2020-06-25 14:48 UTC, merged