学習記録の単体削除
YoshijiFujiwara/himawari-project pull request #164
Opened 2020-06-27 06:50 UTC by shzawa

## :ticket: チケット
(trelloのチケットのリンクを貼りましょう)
https://trello.com/c/YvLObzIr

## :memo: 概要
(やった内容を書こう！)
- 学習記録の削除
  - 投稿者自身のものかどうか
  - 目標と紐付いている学習記録か

## :stuck_out_tongue: やってないこと
（この PR ではやってないことなどを明記しよう。相談の上、あえて他のPRで対応する予定のこととか）
- 目標消したら学習記録まるごと消す

とかその辺

## :heavy_check_mark: 動作確認
（実装した個々の機能の再現方法を明記し、開発者・レビュワー共に確認するのだ！）
- [ ] CIが通ること

エンドポイント -> `(DELETE) /api/goals/:goal_id/commits/:id`

### ログインしている時

- [ ] ユーザーBがユーザーAの学習記録に対してこのエンドポイントを叩こうとして弾かれる(404)
- [ ] ユーザーAが対象の学習記録とは無関係な自分の別の目標IDを指定したら弾かれる(404メッセ付き)
- [ ] ユーザーAが目標に紐付いた学習記録を消そうとしたら204が返ってくる(正常)

- [ ] GET `​/api​/commits`が正常に動いているか
- [ ] GET `/api/commits/summary/monthly`が〃
- [ ] GET `/api/commits/summary/total`が〃

2020-06-27 06:51 UTC, YoshijiFujiwara commented
# [Codecov](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164?src=pr&el=h1) Report
> Merging [#164](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164?src=pr&el=desc) into [develop](https://codecov.io/gh/YoshijiFujiwara/himawari-project/commit/6fd8c6348089eb3ddc5beab7e558fb4d2e4ba05b&el=desc) will **increase** coverage by `22.25%`.
> The diff coverage is `16.66%`.

[![Impacted file tree graph](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164/graphs/tree.svg?width=650&height=150&src=pr&token=ICPqkmgEhz)](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164?src=pr&el=tree)

```diff
@@             Coverage Diff              @@
##           develop     #164       +/-   ##
============================================
+ Coverage    57.24%   79.50%   +22.25%     
============================================
  Files           86       39       -47     
  Lines          952      600      -352     
  Branches        60       28       -32     
============================================
- Hits           545      477       -68     
+ Misses         407      123      -284     
```


| [Impacted Files](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [api/src/commits/commits.service.ts](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164/diff?src=pr&el=tree#diff-YXBpL3NyYy9jb21taXRzL2NvbW1pdHMuc2VydmljZS50cw==) | `59.09% <0.00%> (-13.14%)` | :arrow_down: |
| [api/src/commits/commit.repository.ts](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164/diff?src=pr&el=tree#diff-YXBpL3NyYy9jb21taXRzL2NvbW1pdC5yZXBvc2l0b3J5LnRz) | `55.55% <16.66%> (-3.27%)` | :arrow_down: |
| [api/src/commits/commits.controller.ts](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164/diff?src=pr&el=tree#diff-YXBpL3NyYy9jb21taXRzL2NvbW1pdHMuY29udHJvbGxlci50cw==) | `80.00% <50.00%> (-2.61%)` | :arrow_down: |
| [client/components/atoms/GoToLink.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164/diff?src=pr&el=tree#diff-Y2xpZW50L2NvbXBvbmVudHMvYXRvbXMvR29Ub0xpbmsudnVl) | | |
| [client/pages/goals/\_id/index.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164/diff?src=pr&el=tree#diff-Y2xpZW50L3BhZ2VzL2dvYWxzL19pZC9pbmRleC52dWU=) | | |
| [client/pages/auth/signin\_success.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164/diff?src=pr&el=tree#diff-Y2xpZW50L3BhZ2VzL2F1dGgvc2lnbmluX3N1Y2Nlc3MudnVl) | | |
| [client/components/atoms/SubmitButton.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164/diff?src=pr&el=tree#diff-Y2xpZW50L2NvbXBvbmVudHMvYXRvbXMvU3VibWl0QnV0dG9uLnZ1ZQ==) | | |
| [...t/components/molecules/SelectBoxWithValidation.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164/diff?src=pr&el=tree#diff-Y2xpZW50L2NvbXBvbmVudHMvbW9sZWN1bGVzL1NlbGVjdEJveFdpdGhWYWxpZGF0aW9uLnZ1ZQ==) | | |
| [client/pages/profile.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164/diff?src=pr&el=tree#diff-Y2xpZW50L3BhZ2VzL3Byb2ZpbGUudnVl) | | |
| [...nt/components/organisms/goals/new/PublicRadios.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164/diff?src=pr&el=tree#diff-Y2xpZW50L2NvbXBvbmVudHMvb3JnYW5pc21zL2dvYWxzL25ldy9QdWJsaWNSYWRpb3MudnVl) | | |
| ... and [41 more](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/164/diff?src=pr&el=tree-more) | |

2020-07-01 14:48 UTC, YoshijiFujiwara requested changes
コメントしました！
修正後codegenお願いします！

2020-07-01 14:48 UTC, YoshijiFujiwara commented on api/src/goals/goal.repository.ts
> +  async findByIdAndUser(id: number, user: UserEntity): Promise<GoalEntity> {
上記でgoalIdが不要になったので、こちらのメソッドも不要になると思います

また違う観点で説明すると、
このくらいの処理だとrepositoryに切り出す必要はないかもです

2020-07-01 14:48 UTC, YoshijiFujiwara commented on api/src/commits/commits.controller.ts
> +  @Delete('goals/:goal_id/commits/:id')
ああ、これ実はですね
`/commits/:id`
で良さそうです

単体のリソースをidを指定して削除したりする場合は、親のリソース(今回の場合はgoal)の情報って実はいらないんです！

2020-07-01 14:48 UTC, YoshijiFujiwara commented on api/src/commits/commits.controller.ts
> +    @Param('goal_id', ParseIntPipe) goalId: number,
なので、`goal_id`が不要になります

2020-07-01 14:48 UTC, YoshijiFujiwara commented on api/src/commits/commits.service.ts
> +    const goal = await this.goalRepository.findByIdAndUser(goalId, user);
このgoalのチェックが不要になります

2020-07-01 14:48 UTC, YoshijiFujiwara commented on api/src/commits/commits.service.ts
> +    const commit = await this.commitRepository.findOne({ id, goalId });
ここも素直にcommitのidと、そのcommitの投稿者がログインユーザーかのチェックができればいいと思われます!:parrot:

2020-07-01 15:17 UTC, shzawa commented on api/src/commits/commits.controller.ts
> +  @Delete('goals/:goal_id/commits/:id')
あーめっちゃ律儀にURI設計してました
commitsのidって複合じゃないですもんね確かに

2020-07-01 15:18 UTC, YoshijiFujiwara commented on api/src/commits/commits.controller.ts
> +  @Delete('goals/:goal_id/commits/:id')
まあ、こういうURL設計にしたかったから、
commitControllerとgroupControllerを完全にわけたって感じではありますね

2020-07-01 15:20 UTC, shzawa commented on api/src/commits/commits.service.ts
> +    const commit = await this.commitRepository.findOne({ id, goalId });
ですね！そのcommit_idから親の親であるuserのデータをleft joinして取ってきてwhereでログイン情報と照らし合わせたらいいんですよね

2020-07-01 15:21 UTC, shzawa commented on api/src/goals/goal.repository.ts
> +  async findByIdAndUser(id: number, user: UserEntity): Promise<GoalEntity> {
なんかfindでやらんのであればなるべくrepositoryで切っとくべきでは？って思い込んでました
了解っす！

2020-07-01 15:21 UTC, shzawa commented on api/src/commits/commits.controller.ts
> +  @Delete('goals/:goal_id/commits/:id')
たしかにたしかに

2020-07-01 15:22 UTC, YoshijiFujiwara commented on api/src/commits/commits.service.ts
> +    const commit = await this.commitRepository.findOne({ id, goalId });
親のgoal.user_idを見れば多分行けそう
なので多分left joinとか意識しなくてもいいかもしれないです
findでcommitをとってきて

`commit.goal.userId`
を確認するというのが手軽かもです

2020-07-01 15:32 UTC, shzawa commented on api/src/commits/commits.service.ts
> +    const commit = await this.commitRepository.findOne({ id, goalId });
あ、ほんまや
てかそれなら今までのやつとかも同じようなことしてるし見直されそう、、、？
了解です！！！

2020-07-02 04:47 UTC, shzawa commented
@YoshijiFujiwara 
pushし忘れててましたPR更新しましたー

2020-07-02 04:55 UTC, YoshijiFujiwara commented on api/src/goals/goal.repository.ts
> +  async findByIdAndUser(id: number, user: UserEntity): Promise<GoalEntity> {
これ多分、削除わすれてそう

2020-07-02 04:57 UTC, shzawa commented on api/src/goals/goal.repository.ts
> +  async findByIdAndUser(id: number, user: UserEntity): Promise<GoalEntity> {
Service層のdeleteCommit()末尾に`await this.commitRepository.delete({ id });`って書いてるので動いてるはずなんですが…

2020-07-02 05:02 UTC, YoshijiFujiwara commented on api/src/goals/goal.repository.ts
> +  async findByIdAndUser(id: number, user: UserEntity): Promise<GoalEntity> {
あ、いやすまん
このメソッド自体を消し忘れてるくね？って意味でした
多分、findByIdAndUser
メソッドはどこからも使われてなさそうみが深い

2020-07-02 05:02 UTC, YoshijiFujiwara commented on api/src/goals/goal.repository.ts
> +  async findByIdAndUser(id: number, user: UserEntity): Promise<GoalEntity> {
日本語ややこしい

2020-07-03 05:49 UTC, shzawa commented on api/src/goals/goal.repository.ts
> +  async findByIdAndUser(id: number, user: UserEntity): Promise<GoalEntity> {
あほんまや、けしときます

2020-07-04 07:37 UTC, YoshijiFujiwara approved these changes
LGTM

2020-07-04 07:38 UTC, YoshijiFujiwara commented
対応ありがとう！マージしま

2020-07-04 07:38 UTC, merged