タイムラインヘッダー
YoshijiFujiwara/himawari-project pull request #181
Opened 2020-07-07 02:34 UTC by yufunayufuna

## :ticket: チケット
(trelloのチケットのリンクを貼りましょう)
https://trello.com/c/rY0Xy4MC
## :memo: 概要
(やった内容を書こう！)
style全般
## :stuck_out_tongue: やってないこと
（この PR ではやってないことなどを明記しよう。相談の上、あえて他のPRで対応する予定のこととか）
マージンなど間隔をとってない
アイコンが微妙に違う
## :heavy_check_mark: 動作確認
（実装した個々の機能の再現方法を明記し、開発者・レビュワー共に確認するのだ！）
- [ ] CIが通ること
- [ ] /groups/1にアクセスするとそれっぽいデザインになっている

2020-07-07 02:35 UTC, YoshijiFujiwara commented
# [Codecov](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/181?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`develop@af764b5`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/181/graphs/tree.svg?width=650&height=150&src=pr&token=ICPqkmgEhz)](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/181?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##             develop     #181   +/-   ##
==========================================
  Coverage           ?   50.78%           
==========================================
  Files              ?       76           
  Lines              ?      957           
  Branches           ?       86           
==========================================
  Hits               ?      486           
  Misses             ?      471           
  Partials           ?        0           
```

2020-07-07 03:48 UTC, YoshijiFujiwara requested changes
ちょっと修正点書きました
そのあと、マージンとかをclassに指定する感じで修正お願いします

僕の手元でこの感じまでできたので、これに近づけるようにがんばってみてください！

<img width="1199" alt="スクリーンショット 2020-07-07 12 42 38" src="https://user-images.githubusercontent.com/35862303/86704734-25a97280-c050-11ea-8929-0b3c10dbf598.png">

2020-07-07 03:48 UTC, YoshijiFujiwara commented on client/components/organisms/groups/_id/TimelineHeader.vue
> +  <div class="d-flex justify-space-between cardGreyBg ma-0 pa-0">
ちょっと上にマージンができるのは、この一つ上のコンポーネントのところで修正が必要そうです
https://github.com/YoshijiFujiwara/himawari-project/blob/4896796f393f4434a8972da464fd7da6d38a1fa8/client/pages/groups/_id/index.vue#L4
で、`class="py-4"`を取り除けばいけると思います

また、ついでに、
https://github.com/YoshijiFujiwara/himawari-project/blob/4896796f393f4434a8972da464fd7da6d38a1fa8/client/pages/groups/_id/index.vue#L3
の行を
`<v-col cols="10">`
のように修正しましょうか
ちょっと幅が広くなるを思います

2020-07-07 03:48 UTC, YoshijiFujiwara commented on client/components/organisms/groups/_id/TimelineHeader.vue
> +      <v-btn><v-icon>mdi-brightness-7</v-icon>設定</v-btn>
```
<v-btn color="white"><v-icon>mdi-cog</v-icon>設定</v-btn>
```
で直せそうです

2020-07-08 02:01 UTC, Sui1224 approved these changes
いけてますLGTMM！！！！！

2020-07-08 02:06 UTC, YoshijiFujiwara approved these changes

2020-07-08 02:06 UTC, Sui1224 commented
middleware: 'authenticated'はページコンポーネントでよろ

2020-07-08 02:06 UTC, merged