[プロフィール編集]モーダルのモック作成
YoshijiFujiwara/himawari-project pull request #182
Opened 2020-07-07 02:51 UTC by libra219

## :ticket: チケット
https://trello.com/c/fzLa0xX0

## :memo: 概要
プロフィール編集を押すと編集モーダルを表示

## :stuck_out_tongue: やってないこと
画像をアップロードするアイコンがzeplinにようにできてない

## :heavy_check_mark: 動作確認
（実装した個々の機能の再現方法を明記し、開発者・レビュワー共に確認するのだ！）
- [ ] CIが通ること
- [ ] himawari.dev/profileの「プロフィール編集」ボタンを押すと編集ダイアログが表示
- [ ] カメラアイコンをクリックでファイル選択可能（画像のみになっている）
- [ ] 保存するボタンクリックでアラート「save profile」が表示

2020-07-07 02:52 UTC, YoshijiFujiwara commented
# [Codecov](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182?src=pr&el=h1) Report
> Merging [#182](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182?src=pr&el=desc) into [develop](https://codecov.io/gh/YoshijiFujiwara/himawari-project/commit/540f792d8d5d064d5da448b9434639d12ceea5a2&el=desc) will **decrease** coverage by `2.77%`.
> The diff coverage is `0.00%`.

[![Impacted file tree graph](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182/graphs/tree.svg?width=650&height=150&src=pr&token=ICPqkmgEhz)](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           develop     #182      +/-   ##
===========================================
- Coverage    53.23%   50.46%   -2.78%     
===========================================
  Files           74       77       +3     
  Lines          911      963      +52     
  Branches        76       86      +10     
===========================================
+ Hits           485      486       +1     
- Misses         426      477      +51     
```


| [Impacted Files](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [...components/organisms/profile/ProfileEditDialog.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182/diff?src=pr&el=tree#diff-Y2xpZW50L2NvbXBvbmVudHMvb3JnYW5pc21zL3Byb2ZpbGUvUHJvZmlsZUVkaXREaWFsb2cudnVl) | `0.00% <0.00%> (ø)` | |
| [client/components/organisms/profile/UserInfo.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182/diff?src=pr&el=tree#diff-Y2xpZW50L2NvbXBvbmVudHMvb3JnYW5pc21zL3Byb2ZpbGUvVXNlckluZm8udnVl) | `0.00% <0.00%> (ø)` | |
| [api/src/commits/commits.service.ts](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182/diff?src=pr&el=tree#diff-YXBpL3NyYy9jb21taXRzL2NvbW1pdHMuc2VydmljZS50cw==) | `59.09% <0.00%> (-13.14%)` | :arrow_down: |
| [api/src/commits/commit.repository.ts](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182/diff?src=pr&el=tree#diff-YXBpL3NyYy9jb21taXRzL2NvbW1pdC5yZXBvc2l0b3J5LnRz) | `55.55% <0.00%> (-3.27%)` | :arrow_down: |
| [api/src/commits/commits.controller.ts](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182/diff?src=pr&el=tree#diff-YXBpL3NyYy9jb21taXRzL2NvbW1pdHMuY29udHJvbGxlci50cw==) | `80.00% <0.00%> (-2.61%)` | :arrow_down: |
| [client/pages/goals/\_id/index.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182/diff?src=pr&el=tree#diff-Y2xpZW50L3BhZ2VzL2dvYWxzL19pZC9pbmRleC52dWU=) | `0.00% <0.00%> (ø)` | |
| [.../components/organisms/goals/index/CommitsTable.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182/diff?src=pr&el=tree#diff-Y2xpZW50L2NvbXBvbmVudHMvb3JnYW5pc21zL2dvYWxzL2luZGV4L0NvbW1pdHNUYWJsZS52dWU=) | `0.00% <0.00%> (ø)` | |
| [...nents/organisms/goals/index/CreateCommitDialog.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182/diff?src=pr&el=tree#diff-Y2xpZW50L2NvbXBvbmVudHMvb3JnYW5pc21zL2dvYWxzL2luZGV4L0NyZWF0ZUNvbW1pdERpYWxvZy52dWU=) | `0.00% <0.00%> (ø)` | |
| [...ient/components/organisms/goals/new/CardHeader.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182/diff?src=pr&el=tree#diff-Y2xpZW50L2NvbXBvbmVudHMvb3JnYW5pc21zL2dvYWxzL25ldy9DYXJkSGVhZGVyLnZ1ZQ==) | | |
| [...nt/components/organisms/goals/new/PublicRadios.vue](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182/diff?src=pr&el=tree#diff-Y2xpZW50L2NvbXBvbmVudHMvb3JnYW5pc21zL2dvYWxzL25ldy9QdWJsaWNSYWRpb3MudnVl) | | |
| ... and [5 more](https://codecov.io/gh/YoshijiFujiwara/himawari-project/pull/182/diff?src=pr&el=tree-more) | |

2020-07-07 09:31 UTC, YoshijiFujiwara requested changes
きれいに出来てました！

1点コメントしたので修正お願いします！
アイコンの背景色の設定は、ちょっと`v-file-input`の不具合により設定が出来ないようなので、
いったんこのままで行こうと思います！

2020-07-07 09:31 UTC, YoshijiFujiwara commented on client/components/organisms/profile/ProfileEditDialog.vue
> +  data() {
55行目から59行目の部分が多分使ってないと思うので、削除お願いします:pray:

2020-07-08 02:21 UTC, Sui1224 approved these changes
いけてます！LGTM！！！

2020-07-08 02:23 UTC, YoshijiFujiwara approved these changes

2020-07-08 02:23 UTC, merged