サインイン機能
YoshijiFujiwara/himawari-project pull request #60
Opened 2020-06-05 07:40 UTC by shzawa

## :ticket: チケット
https://trello.com/c/VuNjGao9
https://trello.com/c/oRWdxoxL

## :memo: 概要
ログイン機能。
ログインに成功すればusernameを元に生成したjwt-tokenをResponseBodyに出力

## :stuck_out_tongue: やってないこと
- エラーメッセージの詳細な考慮

## :heavy_check_mark: 動作確認
（実装した個々の機能の再現方法を明記し、開発者・レビュワー共に確認するのだ！）
- [ ] [テスト用入力値一覧](https://docs.google.com/spreadsheets/d/1HxuddEkPaNLYfqVgPsn1EEc_cJ1qIJMbR30ttpSItC0/edit#gid=0)
- [ ] CIが通ること

2020-06-05 10:23 UTC, shzawa commented
さっき言ってた「どのカラムが重複してたか」の情報が抜けてるな…修正しま
っていうのと入力値のバリデーションのunique制約のチェックは値毎に並列で行いたいけどそんなことできるのかはわからん

2020-06-05 12:51 UTC, YoshijiFujiwara commented
サインインは重複していいんやんね？
一応確認ですー

2020-06-05 14:03 UTC, shzawa commented
> サインインは重複していいんやんね？
> 
> 一応確認ですー
> 
> 

あ、馬鹿すぎた SignUpとごっちゃなってた
SignInでは別に値がuniqueかどうかはどうでもいいんでした…

2020-06-05 14:05 UTC, shzawa commented
ヒットするかどうかじゃんっていう
username(email)欄がヒットしなかった場合のこと考えてました
usernameかemailどっちかがヒットしなかった場合文言どないしましょ

2020-06-05 14:06 UTC, shzawa commented
username(email)の場合は「ユーザー名またはメールアドレスが未登録です」
パスワードの場合は「パスワードが違います」
とかでいいですかね文言的に

2020-06-05 14:23 UTC, YoshijiFujiwara commented
githubさんはなんと！
いずれの場合であっても（hoge@hoge.comのようなメールアドレス っぽい文字列であっても）
`ユーザー名またはパスワードが間違っています`
って出るんですな
![スクリーンショット 2020-06-05 23 22 16](https://user-images.githubusercontent.com/35862303/83887465-6b3dfb80-a783-11ea-94fc-417801f4bfa3.png)

なので、それに習って良さそうです

2020-06-05 14:27 UTC, YoshijiFujiwara commented
400系統のエラーレスポンスの場合、フロントでこれを自動で表示してるんじゃねって感じすらしますね
昼に言ってた、`どっちがエラーかわかるように`っていうのは、危険なのかもしれないな:cry:
セキュリティ難しい

今回は、参考にできるgithubのサイトがあるので、それに習うのが良さそう
その上で、エラーメッセージをサーバでもつか、フロントでもつかは、ozawaの方から提案くれると嬉しいです:pray:

2020-06-05 14:47 UTC, shzawa commented
> githubさんはなんと！
> 
> いずれの場合であっても（hoge@hoge.comのようなメールアドレス っぽい文字列であっても）
> 
> `ユーザー名またはパスワードが間違っています`
> 
> って出るんですな
> 
> ![スクリーンショット 2020-06-05 23 22 16](https://user-images.githubusercontent.com/35862303/83887465-6b3dfb80-a783-11ea-94fc-417801f4bfa3.png)
> 
> 
> 
> なので、それに習って良さそうです

あーやっぱそうっすよねセキュリティ的にも

2020-06-05 14:48 UTC, shzawa commented
エラーの振り分けむずいな、、、
ちょっと土日あんまり時間取れなさそうですけど調査と設計考えるやつは進めときます

2020-06-06 03:15 UTC, YoshijiFujiwara requested changes
書き方の部分で良く出来そうなところを一通りコメントしました
確認お願いします！

2020-06-06 03:15 UTC, YoshijiFujiwara commented on api/src/auth/auth.controller.ts
> +    status: 201,
[memo]
確かに、201の方がいいっすね
昨日のレビュー中に気付きましたね

2020-06-06 03:15 UTC, YoshijiFujiwara commented on api/src/auth/auth.controller.ts
> +  signIn(@Body(ValidationPipe) createUserDto: CreateUserDto) {
createUserDtoは、signUp専用のdtoなので、これは別のdtoを用意して置いた方がいいですね
今回の場合だとさらに、
- username, email がどちらかemptyでもいい
という違いがあるので、別のdtoが必要そうです

また、別の観点から説明すると、signUpとsignInは、今後別々の拡張をする可能性が高い（たとえば、エラーメッセージなど）ため
同じパラメータっぽくても、予め分けておいた良さそうです
`見た目が同じだけど、中身が違う`ってやつです

2020-06-06 03:15 UTC, YoshijiFujiwara commented on api/src/auth/auth.module.ts
> +      signOptions: { expiresIn: '1h' },
[memo]
1hって文字列でかけるのか、
3600みたいな書き方しかないと思ってた

2020-06-06 03:15 UTC, YoshijiFujiwara commented on api/src/auth/auth.service.ts
> +    const user = (await (username === undefined))
上記のコメントで、username, emailのどちらかがemptyになってもいいようにしたとすると、
この行の上に、
```
if (!username && !password) {
  throw new UnauthorizedException('hogehoge');
}
```
を仕込む必要がありそうです

2020-06-06 03:15 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +  async passwordVerification(
他のメソッド名が動詞なので、ここだけ名詞になっているのが気になりました
validateなんとかかんとか
が良さそうです

2020-06-06 03:15 UTC, YoshijiFujiwara commented on api/src/auth/auth.service.ts
> +    await this.userRepository.passwordVerification(password, user);
多分、20 ~ 26行目のところって
`passwordVerification `に入れちゃっていいと思います
つまり、validateできればそのユーザーのusername
そうでなければ、nullあたりを返して、
その値をみて`UnauthorizedException`あたりを返すとよさそう:+1:

2020-06-06 03:15 UTC, YoshijiFujiwara commented on api/src/auth/auth.service.ts
> +      access_token: this.jwtService.sign(payload),
nestJSでは、キャメルケースが基本だと思うので、
`accessToken`が良さそうですね

2020-06-06 03:15 UTC, YoshijiFujiwara commented on api/src/auth/auth.service.ts
> +      access_token: this.jwtService.sign(payload),
ちなみに、フロント側に返す都合でスネークケースにするということも今後ありえるとは思いますが、
その用事をserviceに持ち込むと汚れてしまうので避けて行きたいと思っています

そのへんの用事を吸収するのには、serializerがうってつけですね:+1:

2020-06-06 03:15 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +    query.andWhere('users.username = :username', { username });
これ多分
```
 const user = await this.findOne({ username });
```
で行けると思います！
お試しください！

2020-06-06 03:15 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +    query.andWhere('users.email = :email', { email });
これ多分
```
 const user = await this.findOne({ email });
```
で行けると思います！
お試しください！

2020-06-06 03:18 UTC, YoshijiFujiwara commented on api/src/auth/auth.service.ts
> +    await this.userRepository.passwordVerification(password, user);
このServiceのsignUpの責務としては、
- emailとかusernameとかをrepositoryに渡して、正常な値か確認をさせること
- 次にjwtServiceに依頼して、controllerに返すためのトークンをいい感じに作ってもらうこと

ってイメージなので、
username, emailとかの条件分岐などは、repositoryの仕事として押し付けていいと思います

2020-06-06 10:22 UTC, YoshijiFujiwara commented on api/src/auth/auth.controller.ts
> +  signIn(@Body(ValidationPipe) createUserDto: CreateUserDto) {
今ふと思ったのですが、createUserDtoって、フロント側からするとちょっと具体的な名前になってしまっていますね
フロント側からは、**signUp**するために必要な何かってことがわかればいいので、
`createUserDto`ではなく`signUpDto`のような名前にして、少し抽象的にすると良さそうです

基本的にcontrollerのメソッド名までくらいならフロントが知っていてもいいかなという**お気持ち**です

2020-06-08 01:35 UTC, shzawa commented on api/src/auth/user.repository.ts
> +    query.andWhere('users.username = :username', { username });
Done

2020-06-08 01:35 UTC, shzawa commented on api/src/auth/user.repository.ts
> +    query.andWhere('users.email = :email', { email });
Done

2020-06-08 01:36 UTC, shzawa commented on api/src/auth/auth.service.ts
> +    const user = (await (username === undefined))
Done

2020-06-08 01:36 UTC, shzawa commented on api/src/auth/user.repository.ts
> +  async passwordVerification(
validatePasswordにしました~
Done

2020-06-08 01:41 UTC, shzawa commented on api/src/auth/auth.controller.ts
> +  signIn(@Body(ValidationPipe) createUserDto: CreateUserDto) {
> createUserDtoは、signUp専用のdtoなので、これは別のdtoを用意して置いた方がいいですね
> 今回の場合だとさらに、
> 
> * username, email がどちらかemptyでもいい
>   という違いがあるので、別のdtoが必要そうです
> 
> また、別の観点から説明すると、signUpとsignInは、今後別々の拡張をする可能性が高い（たとえば、エラーメッセージなど）ため
> 同じパラメータっぽくても、予め分けておいた良さそうです
> `見た目が同じだけど、中身が違う`ってやつです

Done

2020-06-08 01:41 UTC, shzawa commented on api/src/auth/auth.controller.ts
> +  signIn(@Body(ValidationPipe) createUserDto: CreateUserDto) {
> 今ふと思ったのですが、createUserDtoって、フロント側からするとちょっと具体的な名前になってしまっていますね
> フロント側からは、**signUp**するために必要な何かってことがわかればいいので、
> `createUserDto`ではなく`signUpDto`のような名前にして、少し抽象的にすると良さそうです
> 
> 基本的にcontrollerのメソッド名までくらいならフロントが知っていてもいいかなという**お気持ち**です

Done

2020-06-08 01:42 UTC, shzawa commented on api/src/auth/auth.controller.ts
> +    status: 201,
ﾆｯｺﾘ

2020-06-08 01:45 UTC, shzawa commented on api/src/auth/user.repository.ts
> +  async passwordVerification(
a, `validateSignInPayload`のが良いかな？

2020-06-08 01:56 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +  async passwordVerification(
signinPayloadだと、signin専用って感じが出てしまうので、ちょっと限定しすぎかなあ
validatePasswordでいいんじゃないかな
passwordを検証するための一貫として、usernameやemailでuserを抽出しているだけなので、関数名としては最終目的となるものを示す感じでよさそうです:+1:

2020-06-08 01:57 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +  async passwordVerification(
userの検索はただの手段なので、関数名にはいらないかなって感じ

2020-06-08 03:50 UTC, shzawa commented on api/src/auth/auth.service.ts
> +      access_token: this.jwtService.sign(payload),
serializerの用途なるほど〜〜〜〜〜〜
あざっすaccess_token->accessTokenに修正しました
Done

2020-06-08 03:50 UTC, shzawa commented on api/src/auth/auth.module.ts
> +      signOptions: { expiresIn: '1h' },
人間にﾔｻｼｲ

2020-06-08 03:50 UTC, shzawa commented on api/src/auth/user.repository.ts
> +  async passwordVerification(
Done

2020-06-08 03:50 UTC, shzawa commented on api/src/auth/auth.service.ts
> +      access_token: this.jwtService.sign(payload),
フロントで受け取る値の名前もlowerCamelで良いとのことなのでDone

2020-06-08 03:50 UTC, shzawa commented on api/src/auth/auth.service.ts
> +    await this.userRepository.passwordVerification(password, user);
Done

2020-06-08 12:19 UTC, YoshijiFujiwara requested changes

2020-06-08 12:19 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +    const user = (!username)
ここフォーマットかけると
```
    const user = !username
```
になりそうです

2020-06-08 12:19 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +  async validatePassword(signInUserDto: SingInUserDto): Promise<JwtPayload> {
`validatePassword`関数なので、JwtPayloadまで返すのは仕事がちょっと多い気がします

この関数では、
- validationが成功したら、そのUserEntityあるいはそのusernameを返す
- vaildationが失敗したら、nullとかfalseを返す
とかってしておいて、

そのUserEntiryあるいはusernameをなんのために使うかは、上位のserviceに任せた方が再利用性が増すと思います
https://github.com/YoshijiFujiwara/himawari-project/pull/60#discussion_r436232734
で書いてる感じですね

2020-06-08 12:19 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +  async validatePassword(signInUserDto: SingInUserDto): Promise<JwtPayload> {
この辺りの例外を投げる処理のところなのですが
例外を投げる場所はあまり散らばらせない方がメンテナンスしやすいので、
serviceに任せた方が良さそうです

具体的には、
うまくいかなかったら上記の通りnullなどを返しておく、
AuthServiceではuser情報が返ってこなかった場合にまとめて
```
throw new UnauthorizedException('ユーザー名またはパスワードが違います');
```
をすることで、
repositoryから例外を投げる処理が一掃出来ます

2020-06-08 12:19 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +      const user = await this.findOneOrFail({ email });
ここもfindOneを使っておいて、ユーザーが見つからなければnullを返すでいいと思います。
そして、service側でnullが返ってきたら例外を投げるって感じにしましょうか
ロジック的に例外とみなすかどうかをServiceさんにまかせておいた方が、再利用性があがります

つまり、いないかもしれないユーザーの検索にこのメソッドを使いたい！ってなった場合、
ユーザーが見つからない場合かならずExceptionを投げる今の実装だと、使いにくくなっちゃいます

2020-06-08 12:20 UTC, shzawa commented on api/src/auth/user.repository.ts
> +    const user = (!username)
Done

2020-06-08 12:21 UTC, YoshijiFujiwara commented
@tk-ozawa 例外の扱い方を中心にコメントしたので、確認お願いします
基本的に、repository単体は、言われた通りの業務をこなしてもらって
service側で、それがロジック的に例外かを判断して投げるってイメージで良さそうです

そうすると自然とExceptionの箇所も１箇所になると思います

2020-06-08 12:26 UTC, shzawa commented on api/src/auth/user.repository.ts
> +  async validatePassword(signInUserDto: SingInUserDto): Promise<JwtPayload> {
validatePassword()の返り値の形って、usernameそのまんまの方がいいですかね？
それとも{ username: user.username } とかってobj型でラッピングしたほうが取り回し良い？
(そうすることでconst user = await.~.validatePassword(...);って受け取れるし良さみを感じました)

2020-06-08 12:29 UTC, YoshijiFujiwara commented on api/src/auth/user.repository.ts
> +  async validatePassword(signInUserDto: SingInUserDto): Promise<JwtPayload> {
うーん、その感じの受け取りやすさなら、string型で素直に返してやった方が良さそうかな
objectに変換するとかは、呼び出し側に任せて、シンプルな実装にしたいお気持ちがあります

2020-06-08 12:30 UTC, shzawa commented on api/src/auth/user.repository.ts
> +  async validatePassword(signInUserDto: SingInUserDto): Promise<JwtPayload> {
了解〜

2020-06-08 13:18 UTC, YoshijiFujiwara commented on api/src/auth/strategy/jwt.strategy.ts
> +  async validate(payload: JwtPayload) {
これ、のちのち認証が必要なルートのために必要なので
中身を作っておきましょうか
```
    const { username } = payload;
    const user = await this.userRepository.findOne({ username });

    if (!user) {
      throw new UnauthorizedException();
    }

    return user;
```
みたいな感じであとで使えますね
返り値の方は, `Promise<UserEntity>`になるかな

2020-06-08 13:20 UTC, YoshijiFujiwara commented on api/src/auth/strategy/jwt.strategy.ts
> +      secretOrKey: 'secret',
[memo]
あとで、環境変数化する
チケットはhttps://trello.com/c/CLuw6eZw

2020-06-08 13:24 UTC, shzawa commented on api/src/auth/strategy/jwt.strategy.ts
> +  async validate(payload: JwtPayload) {
今の脳みそだとそれ冗長なのでは？ってなっちゃってるんですけど(死)
現在とはまた別のルートで使う場合このjwt-strategy上でバリデーションが必要なんですね
別のルートどんな感じなのかざっくり知りたいっす

2020-06-08 13:30 UTC, YoshijiFujiwara commented on api/src/auth/strategy/jwt.strategy.ts
> +  async validate(payload: JwtPayload) {
後々、勉強の記録をする処理のところでjwtを渡さないと弾くってことをすると思うのですが、
```
@UseGuards(AuthGuard())
hoge(@Req req) {
  console.log(req)
}
```
の`req`に、jwt.strategyでvalidateしたついでに
ユーザー情報が自動で入るようになります

つまり、だれが記録したのかすぐにわかるようになるわけですね

` async validate`関数でなにも返していないとその情報が得られないので、
また検索しなおさないといけなくなる

といった感じです

2020-06-08 13:30 UTC, shzawa commented on api/src/auth/strategy/jwt.strategy.ts
> +      secretOrKey: 'secret',
azas

2020-06-08 14:32 UTC, YoshijiFujiwara reviewed
これでラストです!

2020-06-08 14:32 UTC, YoshijiFujiwara commented on api/src/auth/dto/sign-in-user.dto.ts
> +  @IsNotEmpty({ message: 'パスワードの入力は必須です' })
エラーメッセージ統一するってことなので、この行を外しましょうか
さらに、passwordは一致しているかどうかが大事なので
```
 @MinLength(8)
  @MaxLength(20)
  @IsNotEmpty({ message: 'パスワードの入力は必須です' })
```
が不要かと思います

usernameの
```
  @MinLength(1)
  @MaxLength(20)
```
も不要かと思います:+1:

2020-06-08 14:49 UTC, shzawa commented on api/src/auth/dto/sign-in-user.dto.ts
> +  @IsNotEmpty({ message: 'パスワードの入力は必須です' })
usernameとpasswordはIsString(), emailはIsEmail()のみってことですか。
ですよね、`ユーザー名またはパスワードが違います`って出すならその辺別に細かくエラー返す必要ないですよね

2020-06-08 14:49 UTC, YoshijiFujiwara commented on api/src/auth/dto/sign-in-user.dto.ts
> +  @IsNotEmpty({ message: 'パスワードの入力は必須です' })
そうそう

2020-06-08 14:51 UTC, shzawa commented on api/src/auth/dto/sign-in-user.dto.ts
> +  @IsNotEmpty({ message: 'パスワードの入力は必須です' })
最低限controller->service->repositoryの各層がデータを受け取った際に型が違うからってエラー吐かさせない為のIsString()やIsEmail()ですね、了解です。

2020-06-09 00:29 UTC, YoshijiFujiwara commented
ファイナルラストコメントです
文字数制限などを
https://docs.google.com/document/d/1lAessaDOXD954nk6M6w34t0-ApQXhKXrcVynapl3GGA/edit
の仕様に合わせるようお願いします！

2020-06-09 04:11 UTC, YoshijiFujiwara approved these changes
![LGTM](https://cdn.lgtmoon.dev/images/87334)

2020-06-09 04:17 UTC, merged